### PR TITLE
Add a few improvements

### PR DESCRIPTION
**Pull request by ray1997**
- Add glyph names database
- Add the ability to show the glyph name; this should address [this issue](https://github.com/EdiWang/Character-Map-UWP/issues/25) and [this issue](https://github.com/EdiWang/Character-Map-UWP/issues/21)
- Add a search option that can access by another button behind search box.
   - In that Search option, it has two options.
      - Enable instant search (Enable by default); this one address [this issue](https://github.com/EdiWang/Character-Map-UWP/issues/27)
      - Search glyph name; this one to address [this issue](https://github.com/EdiWang/Character-Map-UWP/issues/26)

### CODE REVIEW

**Comment by EdiWang** [comment]
Thanks @ray1997 , I'll review this soon.

**Comment by JohnnyWestlake** [comment]
Fwiw, on the Unicode-data branch I've got a more detailed (but unfinished) version of glyph listings, including control characters and full MDL2 listings (and Font Awesome quite soon)

**Comment by ray1997** [comment]
@JohnnyWestlake Well. Should I remove all my change relate to Unicode name and left with only search option? Or maybe discard my pull request entirely?

**Comment by JohnnyWestlake** [comment]
@ray1997 I think from my point of view I shall endeavour to finish my branch up this weekend (it contains other fixes as well), and then at that point perhaps apply your search changes on top of that?

**Comment by EdiWang** [comment]
Based on @JohnnyWestlake 's comment. This PR will wait till @JohnnyWestlake finishes the changes.

**Comment by ray1997** [comment]
I can't figure out how to pull the latest change to here. I'll re-fork and make a change and I'll send another pull request

**Comment by EdiWang** [comment]
Thanks @ray1997 

It may be some merge conflict blocking the pull from origin/master. Otherwise use **git pull origin master** should be good. I usually use GitHub desktop app to do it from UI.

**Pull request closed without merging**
